version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224 # 接続先
        fluentd-async: "true" # これがないとマシンの再起動時に接続エラーが発生する
        tag: "contaier.{{.Name}}" # ログのタグ名
    depends_on:
      - fluent-bit
  fluent-bit:
    container_name: "fluent-bit"
    image: cr.fluentbit.io/fluent/fluent-bit:2.1.10
    volumes:
      - ./fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./data:/tmp
    ports:
      - 24224:24224
