version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: "docker.{{.Name}}"
        fluentd-async: "true"
    depends_on:
      - fluentd
  fluentd:
    image: fluent/fluentd:v1.16.2-1.0
    volumes:
      - ./config:/fluentd/etc
    ports:
      - 24224:24224
      - 24224:24224/udp
