version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: "docker.{{.Name}}"
        fluentd-async: "true"
    depends_on:
      - fluentd
  fluentd:
    container_name: "fluentd"
    build: ./fluentd
    volumes:
      - ./fluentd/config:/fluentd/etc
    depends_on:
      - elasticsearch
    ports:
      - 24224:24224
      - 24224:24224/udp
  elasticsearch:
    container_name: elasticsearch
    build: ./elasticsearch
    environment:
      - cluster.name=es-cluster # Cluster名
      - node.name=es01 # Node名
      - discovery.type=single-node # Default: multi-node
      # Elasticsearchが複数ノードクラスターを形成するかどうかの指定
      - xpack.security.enabled=false # セキュリティ機能の有効/無効
      - bootstrap.memory_lock=true # メモリスワップの禁止
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # JavaVMのヒープサイズ
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200 # HTTP Port
      - 9300:9300 # Transport TCP Port
    volumes:
      - esdata:/usr/share/elasticsearch/data
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.9.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
volumes:
  esdata: # Elasticsearch log data
    driver: local
